[tool.poetry]
name = "fitlife"
version = "0.1.0"
description = ""
authors = ["Maksym Osinskyi <maximosinskiy@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.119.0"}
pydantic-settings = "^2.11.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-jose = "^3.5.0"
uvicorn = "^0.38.0"
aiosqlite = "^0.21.0"
sqlalchemy = "^2.0.44"
greenlet = "^3.2.4"
redis = "^7.1.0"
python-dotenv = "^1.2.1"
fastapi-cache2 = "^0.2.2"
email-validator = "^2.3.0"
alembic = "^1.18.3"
bcrypt = "4.0.1"
sqladmin = {extras = ["full"], version = "^0.23.0"}
itsdangerous = "^2.2.0"
asyncpg = "^0.31.0"
celery = "^5.4.0"
celery-types = "^0.26.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
pytest-cov = "^6.0.0"
httpx = "^0.28.0"
pre-commit = "^4.0.0"
black = "^24.10.0"
isort = "^5.13.0"
ruff = "^0.8.0"
mypy = "^1.13.0"
bandit = "^1.7.0"
pytest-asyncio = "^1.3.0"

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "migrations",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 88
indent-width = 4

target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"

indent-style = "space"

skip-magic-trailing-comma = false

line-ending = "auto"

docstring-code-format = false

docstring-code-line-length = "dynamic"

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
warn_unused_ignores = true
disallow_untyped_defs = true
no_implicit_optional = true
strict = true

exclude = [
    "venv/",
    "build/",
    "tests",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
