[tool.poetry]
name = "fitlife"
version = "0.1.0"
description = ""
authors = ["Maksym Osinskyi <maximosinskiy@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.119.0"}
pydantic-settings = "^2.11.0"
passlib = "^1.7.4"
python-jose = "^3.5.0"
uvicorn = "^0.38.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
httpx = "^0.28.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
