"""refactor_pass_features_to_entities

Revision ID: 073d924cbfcd
Revises: 2d0f247f0f97
Create Date: 2026-05-26 22:38:11.148093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '073d924cbfcd'
down_revision: Union[str, Sequence[str], None] = '2d0f247f0f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_features',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pass_feature_association',
    sa.Column('pass_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['pass_features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pass_id', 'feature_id')
    )
    op.drop_column('passes', 'features')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passes', sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('pass_feature_association')
    op.drop_table('pass_features')
    # ### end Alembic commands ###
