"""replace coach emoji with image_url

Revision ID: 378a30f334ed
Revises: b579158c279d
Create Date: 2026-05-23 17:26:46.529992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378a30f334ed'
down_revision: Union[str, Sequence[str], None] = 'b579158c279d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('image_url', sa.String(), nullable=False, server_default=''))
    op.drop_column('coaches', 'emoji')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('emoji', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('coaches', 'image_url')
    # ### end Alembic commands ###
