"""Change password lenght to 255

Revision ID: 3fc5901f1d06
Revises: 8631e0741f55
Create Date: 2026-02-02 14:48:44.850523

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '3fc5901f1d06'
down_revision: str | Sequence[str] | None = '8631e0741f55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
