"""Add speciality and emoji_entity to coach

Revision ID: 56e1252ed248
Revises: d53d9914cfe3
Create Date: 2026-03-16 13:31:49.428312

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56e1252ed248'
down_revision: str | Sequence[str] | None = 'd53d9914cfe3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'Спеціальність',
                sa.String(),
                server_default='Силові тренування',
                nullable=False,
                comment='Силові тренування, Функціональний фітнес, Йога та стретчинг, Кардіо та HIIT',
            )
        )
        batch_op.add_column(
            sa.Column('Emoji', sa.String(), server_default='&#x1F3CB;', nullable=False, comment='HTML entity (hex)')
        )

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('coach_id', existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('coach_id', existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_column('Emoji')
        batch_op.drop_column('Спеціальність')

    # ### end Alembic commands ###
