"""Add experience_title to coach

Revision ID: 6d5d83724f32
Revises: e89438a5ff00
Create Date: 2026-03-16 13:58:23.248400

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6d5d83724f32'
down_revision: str | Sequence[str] | None = 'e89438a5ff00'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_title', sa.String(), server_default='рік', nullable=False))

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('coach_id', existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('coach_id', existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_column('experience_title')

    # ### end Alembic commands ###
