"""Add training session.

Revision ID: 6d855b693408
Revises: 3fc5901f1d06
Create Date: 2026-02-02 15:36:12.448124

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6d855b693408'
down_revision: str | Sequence[str] | None = '3fc5901f1d06'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'training_sessions',
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('max_participants', sa.Integer(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('coach_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ['coach_id'],
            ['coaches.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'session_participants',
        sa.Column('session_id', sa.Uuid(), nullable=False),
        sa.Column('member_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ['member_id'],
            ['members.id'],
        ),
        sa.ForeignKeyConstraint(
            ['session_id'],
            ['training_sessions.id'],
        ),
        sa.PrimaryKeyConstraint('session_id', 'member_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_participants')
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
