"""Rename password_hash to password.

Revision ID: 8631e0741f55
Revises: 317cd52983ed
Create Date: 2026-02-01 19:02:19.989819

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8631e0741f55'
down_revision: str | Sequence[str] | None = '317cd52983ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('coaches', 'password_hash')
    op.add_column('members', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('members', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('password_hash', sa.VARCHAR(), nullable=False))
    op.drop_column('members', 'password')
    op.add_column('coaches', sa.Column('password_hash', sa.VARCHAR(), nullable=False))
    op.drop_column('coaches', 'password')
    # ### end Alembic commands ###
