"""Implement Base and UserBase models.

Revision ID: 87ffce6fdd0d
Revises: cb1bdf1cb7cd
Create Date: 2026-03-21 21:01:39.374130

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '87ffce6fdd0d'
down_revision: str | Sequence[str] | None = 'cb1bdf1cb7cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
