"""Change uuid4 to uuid4().

Revision ID: a512c5c7f56c
Revises: 6022684f7ee1
Create Date: 2026-03-22 10:19:39.057806

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a512c5c7f56c'
down_revision: str | Sequence[str] | None = '6022684f7ee1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    # ### end Alembic commands ###
