"""Change session times to datetime

Revision ID: b579158c279d
Revises: 498945b1fd7f
Create Date: 2026-05-12 14:25:27.280340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b579158c279d'
down_revision: Union[str, Sequence[str], None] = '498945b1fd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE training_sessions ALTER COLUMN start_time TYPE TIMESTAMP WITH TIME ZONE USING (CURRENT_DATE + start_time)::TIMESTAMP WITH TIME ZONE")
    op.execute("ALTER TABLE training_sessions ALTER COLUMN end_time TYPE TIMESTAMP WITH TIME ZONE USING (CURRENT_DATE + end_time)::TIMESTAMP WITH TIME ZONE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_sessions', 'end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('training_sessions', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
