"""Implement Base and UserBase models.

Revision ID: cb1bdf1cb7cd
Revises:
Create Date: 2026-03-21 17:29:13.716883

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'cb1bdf1cb7cd'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
