"""Change uuid4() to uuid.

Revision ID: ceda745deb78
Revises: 6022684f7ee1
Create Date: 2026-03-22 14:02:09.534524

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ceda745deb78'
down_revision: str | Sequence[str] | None = '6022684f7ee1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_coaches_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaches_phone_number'), ['phone_number'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_members_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_phone_number'), ['phone_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_phone_number'))
        batch_op.drop_index(batch_op.f('ix_members_email'))
        batch_op.alter_column('id', existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coaches_phone_number'))
        batch_op.drop_index(batch_op.f('ix_coaches_email'))
        batch_op.alter_column('id', existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    # ### end Alembic commands ###
