"""Change coach specialization to array

Revision ID: d2d18aec74f8
Revises: 2e72bd743b12
Create Date: 2026-05-09 17:52:37.711689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2d18aec74f8'
down_revision: Union[str, Sequence[str], None] = '2e72bd743b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('specializations', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('coaches', 'specialization')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('coaches', 'specializations')
    # ### end Alembic commands ###
