"""Create training_session model and session_participant.

Revision ID: e25de3c750cb
Revises: ceda745deb78
Create Date: 2026-03-25 08:45:40.467041

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e25de3c750cb'
down_revision: str | Sequence[str] | None = 'ceda745deb78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    # ### end Alembic commands ###
