"""Add experience to coach

Revision ID: e89438a5ff00
Revises: 56e1252ed248
Create Date: 2026-03-16 13:37:06.058338

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e89438a5ff00'
down_revision: str | Sequence[str] | None = '56e1252ed248'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'Досвід', sa.Integer(), nullable=False, comment='Потрібно ввести досвід в роках', server_default='1'
            )
        )

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('coach_id', existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('coach_id', existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_column('Досвід')

    # ### end Alembic commands ###
