"""Rename TrainingSession to TrainingSessionModel.

Revision ID: f42caf362feb
Revises: 19f380a97464
Create Date: 2026-02-07 20:01:52.983973

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f42caf362feb'
down_revision: str | Sequence[str] | None = '19f380a97464'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('coach_id', existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('coach_id', existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    # ### end Alembic commands ###
